"""Описание изменений

Revision ID: 80efb544a961
Revises: d9df677183cd
Create Date: 2026-01-09 04:38:35.825134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80efb544a961'
down_revision = 'd9df677183cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
